### ISSUE TITLE
Can't store files

### ISSUE THREAD

**Issue by mmohorko** [fairDataSociety/Fairdrop#174] opened 2019-09-16 08:44 UTC
FD version 0.4.0. - testing on staging ... I stored a file, but it does not appear under my stored files.

**Comment by significance** [comment] 2019-09-16 09:29
just tested this and couldn't reproduce

@mmohorko does this happen consistently for you? if so would you be able to share the mailbox file and password with me over DM please?

**Comment by mmohorko** [comment] 2019-09-16 11:36
Tried again and it works now. Don't know what I did wrong the first time. But we can close this issue.

**Comment by crtahlin** [comment] 2019-09-16 14:06
@mmohorko please close the issue, since you poened it. If you cannnot (no permission?) let me know.

**Closed** 2019-09-17 12:46 UTC
